id: P002982
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09977
  title: རྫོང་གཏེར་ཀུན་བཟང་ཉི་མའི་གསུང་སྐོར་གཅེས་བསྡུས་
  author: ''
  volumes:
    db0ab837131b41c5953c347dd7035583:
      image_group_id: I00KG010136
      title: ''
      volume_number: 1
      total_pages: 394
